# Build stage
FROM node:alpine AS builder
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app

# Production stage
FROM node:alpine
WORKDIR /app
COPY --from=builder /app /app

CMD ["node", "main.js"]